title: "Toluna IP Platform"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
heading_anchors: true
aux_links:
  "Contact Us":
    - "http://docs.integratedpanel.toluna.com/contactus/"